### ISSUE TITLE
APY calculation is completely inaccurate + harmful

### ISSUE THREAD

**Issue by bji** [solana-beach/issue-tracker#36]
**Describe the bug**

There is an APY column on solanabeach.io in the validators view.  Not sure what it takes for this to appear because I just noticed it recently.  Might not be shown to every user in every situation (such as window size)?

The values shown there are totally inaccurate in every way.

Please stop showing inaccurate data here, this is not acceptable.

**Comment by bji** [comment]
You should just fetch APY data from stakeview.app.  You can get it according to this document:

https://stakeview.app/data.html

This data has been proven accurate for a long time.  There is no need to re-invent the wheel here, especially when you are re-inventing that wheel with significant flaws.

**Comment by rpd089** [comment]
Hey @bji, thanks for creating this ticket and also reaching out via discord. Your input is always very welcome. 

Just for context, the way we calculate the APY per validator right now is based on the official formula, which we took from the docs (https://docs.solana.com/inflation/terminology). We adjusted the inflation to account for actual slot times that were achieved during the past 24h of network activity. 

We'll however take it down for now since the last thing we want is to confuse anyone here. 

Thanks for the link, too! However, the dataset is not accessible for recent epochs (https://stakeview.app/apy/<EPOCH_NUMBER>.json returns access denied for 267,266 etc), but it is available in the prev3.json

**Comment by bji** [comment]
> Hey @bji, thanks for creating this ticket and also reaching out via discord. Your input is always very welcome.
> 
> Just for context, the way we calculate the APY per validator right now is based on the official formula, which we took from the docs (https://docs.solana.com/inflation/terminology). We adjusted the inflation to account for actual slot times that were achieved during the past 24h of network activity.
> 
> We'll however take it down for now since the last thing we want is to confuse anyone here.
> 
> Thanks for the link, too! However, the dataset is not accessible for recent epochs (https://stakeview.app/apy/<EPOCH_NUMBER>.json returns access denied for 267,266 etc), but it is available in the prev3.json

Hm not sure what problems you were having fetching the JSON?  I had no problem getting it for these URLs:

https://stakeview.app/apy/267.json
https://stakeview.app/apy/266.json

And for the current epoch (282):

https://stakeview.app/apy/282.json

No problem either.

```$ curl -s -o- https://stakeview.app/apy/267.json | wc -c
177636
```

**Comment by bji** [comment]
Closing so I don't have to look at it in my list of Pull Requests anymore, given that Staking Facilities will never take action on this.
